name: Client tests

on: [ push, pull_request ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./client/mini-spotify/package-lock.json

      - name: Cliet npm ci
        run: npm ci
        working-directory: ./client/mini-spotify
      
      - name: Client's server npm ci
        run: npm ci
        working-directory: ./server
        
      - name: Cliet npm build
        run: npm run build
        working-directory: ./client/mini-spotify
        
      - name: Run unit tests
        run: npm run test Components
        working-directory: ./client/mini-spotify
        
      - name: run e2e tests
        run: |
          cd ./client/mini-spotify && npm start &
          cd ./server && npm start &
          sleep 10
          cd ./client/mini-spotify && npx playwright test
